version: "3.8"

services:
  fastapi:
    build: .
    container_name: yolo_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app/datasets:/app/datasets  # Данные сохраняются между перезапусками
    restart: always